from __future__ import annotations

from ..models import ScanResult, Severity

_SEV_COLOR = {
    Severity.CRITICAL: "#dc3545",
    Severity.HIGH: "#fd7e14",
    Severity.MEDIUM: "#ffc107",
    Severity.LOW: "#0dcaf0",
    Severity.UNKNOWN: "#6c757d",
}

_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>CyberScanner Report</title>
<style>
  *{{box-sizing:border-box;margin:0;padding:0}}
  body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#0f172a;color:#e2e8f0;padding:24px}}
  h1{{font-size:1.4rem;color:#f1f5f9}}
  h2{{font-size:1rem;color:#cbd5e1;margin-bottom:12px}}
  .header{{background:#1e293b;border-radius:10px;padding:24px;margin-bottom:20px;border-left:4px solid #6366f1}}
  .meta{{color:#94a3b8;font-size:0.82rem;margin-top:6px}}
  code{{background:#0f172a;padding:2px 6px;border-radius:3px;font-size:0.8rem;font-family:monospace}}
  .badges{{display:flex;gap:12px;flex-wrap:wrap;margin-bottom:20px}}
  .badge{{background:#1e293b;border-radius:8px;padding:14px 20px;text-align:center;min-width:90px}}
  .badge .n{{font-size:1.8rem;font-weight:700}}
  .badge .l{{font-size:0.7rem;color:#94a3b8;text-transform:uppercase;letter-spacing:.05em;margin-top:2px}}
  .section{{background:#1e293b;border-radius:10px;padding:20px;margin-bottom:20px}}
  table{{width:100%;border-collapse:collapse}}
  th{{text-align:left;padding:8px 10px;color:#64748b;font-size:0.72rem;text-transform:uppercase;border-bottom:1px solid #334155}}
  td{{padding:9px 10px;border-bottom:1px solid #0f172a;font-size:0.84rem;vertical-align:top}}
  tr:last-child td{{border-bottom:none}}
  tr:hover td{{background:#162032}}
  .sev{{display:inline-block;padding:2px 7px;border-radius:4px;font-size:0.68rem;font-weight:700;letter-spacing:.04em}}
  .vid{{font-family:monospace;color:#818cf8}}
  .fix{{color:#22c55e;font-family:monospace;font-size:0.78rem}}
  .empty{{color:#475569;text-align:center;padding:28px;font-style:italic}}
  .footer{{color:#475569;font-size:0.75rem;text-align:center;margin-top:16px}}
</style>
</head>
<body>
<div class="header">
  <h1>CyberScanner Security Report</h1>
  <p class="meta">Target: <code>{target_path}</code>&nbsp;&nbsp;|&nbsp;&nbsp;Scan ID: <code>{scan_id}</code>&nbsp;&nbsp;|&nbsp;&nbsp;{timestamp}</p>
</div>
<div class="badges">{badges}</div>
{vuln_section}
{secrets_section}
<div class="footer">Generated by cyberscanner &mdash; open-source vulnerability scanner</div>
</body>
</html>"""


def to_html(result: ScanResult) -> str:
    s = result.summary

    def badge(count: int, label: str, color: str) -> str:
        return (
            f'<div class="badge">'
            f'<div class="n" style="color:{color}">{count}</div>'
            f'<div class="l">{label}</div>'
            f"</div>"
        )

    badges = "".join([
        badge(s.packages_scanned, "Packages", "#6366f1"),
        badge(s.total_vulnerabilities, "Vulns", "#dc3545"),
        badge(s.critical, "Critical", _SEV_COLOR[Severity.CRITICAL]),
        badge(s.high, "High", _SEV_COLOR[Severity.HIGH]),
        badge(s.medium, "Medium", _SEV_COLOR[Severity.MEDIUM]),
        badge(s.low, "Low", _SEV_COLOR[Severity.LOW]),
        badge(s.total_secrets, "Secrets", "#7c3aed"),
    ])

    if result.vulnerabilities:
        rows = ""
        for v in result.vulnerabilities:
            c = _SEV_COLOR.get(v.severity, "#6c757d")
            fix = " ".join(f"→{f}" for f in v.fixed_in) if v.fixed_in else "—"
            rows += (
                f"<tr>"
                f'<td><span class="sev" style="background:{c}22;color:{c}">{v.severity.value}</span></td>'
                f"<td><strong>{v.package}</strong></td>"
                f"<td><code>{v.version}</code></td>"
                f'<td><span class="vid">{v.vuln_id}</span></td>'
                f"<td>{v.title[:80]}</td>"
                f'<td class="fix">{fix}</td>'
                f"</tr>"
            )
        vuln_section = (
            f'<div class="section"><h2>Vulnerabilities ({len(result.vulnerabilities)})</h2>'
            f"<table><thead><tr>"
            f"<th>Severity</th><th>Package</th><th>Version</th><th>Vuln ID</th><th>Title</th><th>Fix</th>"
            f"</tr></thead><tbody>{rows}</tbody></table></div>"
        )
    else:
        vuln_section = '<div class="section"><div class="empty">✓ No vulnerabilities found</div></div>'

    if result.secrets:
        rows = ""
        for sec in result.secrets:
            c = _SEV_COLOR.get(sec.severity, "#6c757d")
            rows += (
                f"<tr>"
                f'<td><span class="sev" style="background:{c}22;color:{c}">{sec.severity.value}</span></td>'
                f"<td>{sec.pattern_name}</td>"
                f"<td><code>{sec.file_path}</code></td>"
                f"<td>{sec.line_no}</td>"
                f"<td><code>{sec.snippet[:80]}</code></td>"
                f"</tr>"
            )
        secrets_section = (
            f'<div class="section"><h2>Secrets Detected ({len(result.secrets)})</h2>'
            f"<table><thead><tr>"
            f"<th>Severity</th><th>Type</th><th>File</th><th>Line</th><th>Preview</th>"
            f"</tr></thead><tbody>{rows}</tbody></table></div>"
        )
    else:
        secrets_section = '<div class="section"><div class="empty">✓ No secrets detected</div></div>'

    return _HTML.format(
        target_path=result.target_path,
        scan_id=result.scan_id,
        timestamp=result.timestamp.strftime("%Y-%m-%d %H:%M UTC"),
        badges=badges,
        vuln_section=vuln_section,
        secrets_section=secrets_section,
    )
